DOMAIN = "energetyczny_kompas_pse"
DEFAULT_UPDATE_INTERVAL = 6

STATE_MAPPING = {
    0: "ZALECANE UŻYTKOWANIE",
    1: "NORMALNE UŻYTKOWANIE",
    3: "ZALECANE OSZCZĘDZANIE",
    4: "WYMAGANE OGRANICZANIE"
}
